### ISSUE TITLE
remove names from AD servers in script

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/garbagecollector#12]
@Jfach 

We have some names for AD servers that are ISE organization names we will want to scrub out.  For this repo, we'd want to set some variable for those names (so that it can be universal.)

Ideas?  like - use an AD seed file for putting AD servers (similar to the netblocks?)

```python
ad_test1 = ad_server.AD_Server('TC-AD01')
ad_test2 = ad_server.AD_Server('TC-AD02')
ad_prod1 = ad_server.AD_Server('TD-AD01')
ad_prod2 = ad_server.AD_Server('TC-AD02')
ad_servers = [ad_test1, ad_test2, ad_prod1, ad_prod2]
```

**Comment by sometheycallme** [comment]
in https://github.com/cleanerbot/garbagecollector/blob/master/scripts/asset_collect.py

**Comment by sometheycallme** [comment]
@Jfach 

In our private repo - have you taken any stabs at decoupling the AD/LDAP servers (seeder)?

I'm in my virtual lab right now hacking at using a seeder file similiar to the networks.txt for this.

**Comment by Jfach** [comment]
@sometheycallme See PR #14 in response to this issue. I have had success using a networks.txt style approach in private repo. Will make another P.R. when all data has been scrubbed from that.

**Comment by sometheycallme** [comment]
merged.

**Comment by sometheycallme** [comment]
@jfach  I merged the pull request.  You will have to rebase your changes from upstream.
