### ISSUE TITLE
asset-collect.py doesn't scan all discovered ips

### ISSUE THREAD

**Issue by Jfach** [cleanerbot/garbagecollector#6]
there is a problem with the way you are constructing some of your loops, as the dns_dict gets overwritten as well as the data held in the results variable. I changed them both to lists instead. Check out this patch on my fork: https://github.com/Jfach/garbagecollector/tree/Jfach-patch-1

**Comment by sometheycallme** [comment]
I merged you PR

**Comment by Jfach** [comment]
closed with 8c6de0a
