### ISSUE TITLE
propose: add CI tests

### ISSUE THREAD

**Issue by jumanjiman** [cleanerbot/garbagecollector#8]
@sometheycallme @jfach

i was thinking to add:

* pep8 tests for python, probably with py-nose similar to https://github.com/dgoodwin/tito/tree/master/test/unit
* add http://editorconfig.org/ config
* add circle.yml to run on every PR

thoughts?

**Comment by Jfach** [comment]
+1 for pep8 tests

**Comment by sometheycallme** [comment]
Thanks @jumanjiman for the suggestions and for working with @jfach on circle Integration !

**Comment by sometheycallme** [comment]
added.
